---
- job:
    name: openstack-simple-stress-test
    pre-run: playbooks/pre-test.yml
    run: playbooks/test.yml
    timeout: 14400
    roles:
      - zuul: osism/zuul-jobs
        name: devstack

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - flake8
        - mypy
        - openstack-simple-stress-test
        - python-black
        - tox:
            vars:
              tox_envlist: test
        - yamllint
    gate:
      jobs:
        - flake8
        - mypy
        - openstack-simple-stress-test
        - python-black
        - tox:
            vars:
              tox_envlist: test
        - yamllint
    periodic-daily:
      jobs:
        - flake8
        - mypy
        - openstack-simple-stress-test
        - python-black
        - tox:
            vars:
              tox_envlist: test
        - yamllint
