---
- name: Stress test play
  hosts: all

  vars:
    zuul_work_dir: "{{ zuul.project.src_dir }}"

  roles:
    - role: tox
      vars:
        tox_extra_args: -- --cloud openstack --image cirros --debug --no-wait
